### ISSUE TITLE
perf ci issues

### ISSUE THREAD

**Issue by Tiecoon** [Tiecoon/B7#33]
`running 1 test
ERROR b7::perf: perf_event_open failed!
error: test failed, to rerun pass '--test run_wyvern'
The command "cargo test" exited with 255.`

see if we can resolve the perf issues on travis
It may be either kernel missing perf support or the perf paranoia level being wrong

https://travis-ci.org/Tiecoon/B7/builds/485195460?utm_source=github_status&utm_medium=notification

**Comment by Tiecoon** [comment]
https://docs.travis-ci.com/user/running-build-in-debug-mode/

**Comment by Tiecoon** [comment]
Perf confirmed not working on Travis, I doubt other ci will be different. Maybe look into hosting custom ci.

**Comment by twizmwazin** [comment]
Might want to consider sr.ht. The guy that runs it might be open to working with you

**Comment by Tiecoon** [comment]
Ideally the ci would atleast do linux/windows builds and as far as I can tell sourcehut only does linux and bsds.

Right now its looking like gitlab runner is a decent option.
